[package]
name = "geos"
version = "2.0.2"
authors = ["Matthieu Viry <matthieu.viry@cnrs.fr>", "Adrien Matissart <a.matissart@qwantresearch.com>", "Antoine Desbordes <antoine.desbordes@gmail.com>", "Guillaume Pinot <texitoi@texitoi.eu>"]
license = "MIT"
repository = "https://github.com/georust/geos"
keywords = ["geos", "libgeos", "geometry", "geography", "gis"]
categories = ["external-ffi-bindings", "algorithms"]
description = "Rust bindings for GEOS C API"
readme = "README.md"
build = "build.rs"

[dependencies]
libc = "0.2"
num = "0.1"
geo-types = "0.1"
failure = "0.1"
failure_derive = "0.1"
enum-primitive-derive = "^0.1"
num-traits = "^0.1"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"
